---
- name: Deploy WAR to native Tomcat
  hosts: all
  gather_facts: false
  vars:
    tomcat_host: localhost
    tomcat_port: 8082
    tomcat_user: deployer
    tomcat_password: change-me
    tomcat_context: /country
    artifact: target/country.service-0.0.1-SNAPSHOT.war

  tasks:
    - name: Assert artifact exists
      stat:
        path: "{{ artifact }}"
      register: war_stat

    - name: Fail if WAR missing
      fail:
        msg: "WAR not found at {{ artifact }}"
      when: not war_stat.stat.exists

    # Deploy using Tomcat Manager text API (PUT upload)
    - name: Deploy WAR via Tomcat Manager (PUT)
      ansible.builtin.uri:
        url: "http://{{ tomcat_user }}:{{ tomcat_password }}@{{ tomcat_host | default('localhost') }}:{{ tomcat_port }}/manager/text/deploy?path=/{{ tomcat_context | regex_replace('^/', '') }}&update=true"
        method: PUT
        headers:
          Content-Type: application/octet-stream
        body: "{{ lookup('file', artifact) }}"
        body_format: raw
        force_basic_auth: true
        status_code: 200
        return_content: true
      register: deploy_result
      no_log: true  

    - name: Show manager response
      debug:
        var: deploy_result.content

    # (Optional) quick smoke check against your API
    - name: Wait for app to come up
      uri:
        url: "http://{{ tomcat_host }}:{{ tomcat_port }}{{ tomcat_context }}/getcountries"
        method: GET
        status_code: [200, 302]
      register: smoke
      retries: 15
      delay: 2
      until: smoke.status in [200, 302]
